In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('raw_data/chicago.csv')

### Split date column into Weekend (Yes or No - i.e. incident falls on a Friday 5pm onwards, to Sun to midnight (11:59pm)) -Madhup

In [4]:
df.head()

,CASE#,DATE OF OCCURRENCE,BLOCK,IUCR,PRIMARY DESCRIPTION,SECONDARY DESCRIPTION,LOCATION DESCRIPTION,ARREST,DOMESTIC,BEAT,WARD,FBI CD,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,JH117298,01/16/2024 01:00:00 AM,038XX W DIVERSEY AVE,0810,THEFT,OVER $500,STREET,N,N,2524,35,06,1150337.0,1918345.0,41.931844,-87.722951,"(41.931843966, -87.722950868)"
1,JG561057,12/31/2023 04:30:00 PM,004XX N WABASH AVE,0460,BATTERY,SIMPLE,STREET,N,N,1834,42,08B,1176592.0,1902931.0,41.888994,-87.626935,"(41.888993854, -87.626934833)"
2,JH117691,01/16/2024 06:50:00 PM,010XX W 99TH ST,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,STREET,Y,N,2232,21,15,1170976.0,1839080.0,41.713905,-87.649425,"(41.713904887, -87.649424515)"
3,JG522770,11/30/2023 07:28:00 AM,034XX W CHICAGO AVE,2024,NARCOTICS,POSSESS - HEROIN (WHITE),ALLEY,Y,N,1121,27,18,1153117.0,1905117.0,41.895490,-87.713086,"(41.895490399, -87.713086271)"
4,JG560426,12/31/2023 12:55:00 AM,0000X W GRAND AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,STREET,Y,N,1831,42,15,1175975.0,1903895.0,41.891653,-87.629172,"(41.891653037, -87.62917162)"

In [5]:
df['DATE  OF OCCURRENCE'] = pd.to_datetime(df['DATE  OF OCCURRENCE'])

In [6]:
df['WEEKDAY'] = df['DATE  OF OCCURRENCE'].dt.strftime('%A')

In [9]:
df.head(2)

,CASE#,DATE OF OCCURRENCE,BLOCK,IUCR,PRIMARY DESCRIPTION,SECONDARY DESCRIPTION,LOCATION DESCRIPTION,ARREST,DOMESTIC,BEAT,WARD,FBI CD,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION,WEEKDAY,WEEKDAY NUM
0,JH117298,2024-01-16 01:00:00,038XX W DIVERSEY AVE,0810,THEFT,OVER $500,STREET,N,N,2524,35,06,1150337.0,1918345.0,41.931844,-87.722951,"(41.931843966, -87.722950868)",Tuesday,1
1,JG561057,2023-12-31 16:30:00,004XX N WABASH AVE,0460,BATTERY,SIMPLE,STREET,N,N,1834,42,08B,1176592.0,1902931.0,41.888994,-87.626935,"(41.888993854, -87.626934833)",Sunday,6

In [8]:
df['WEEKDAY NUM'] = df['DATE  OF OCCURRENCE'].dt.weekday

In [10]:
df['WEEKEND'] = np.where(df['WEEKDAY NUM'] <= 4, 'NO','YES')

In [15]:
df.head(2)

,CASE#,DATE OF OCCURRENCE,BLOCK,IUCR,PRIMARY DESCRIPTION,SECONDARY DESCRIPTION,LOCATION DESCRIPTION,ARREST,DOMESTIC,BEAT,WARD,FBI CD,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION,WEEKDAY,WEEKDAY NUM
0,JH117298,2024-01-16 01:00:00,038XX W DIVERSEY AVE,0810,THEFT,OVER $500,STREET,N,N,2524,35,06,1150337.0,1918345.0,41.931844,-87.722951,"(41.931843966, -87.722950868)",Tuesday,1
1,JG561057,2023-12-31 16:30:00,004XX N WABASH AVE,0460,BATTERY,SIMPLE,STREET,N,N,1834,42,08B,1176592.0,1902931.0,41.888994,-87.626935,"(41.888993854, -87.626934833)",Sunday,6

In [14]:
df.drop(['WEEKEND'],axis=1,inplace = True)

In [18]:
# Extract day of week and hour

df['hour'] = df['DATE  OF OCCURRENCE'].dt.hour

# Use conditions to determine 'Weekend'
df['WEEKEND'] = (
    (df['WEEKDAY NUM'] == 4) & (df['hour'] >= 17) |  # Friday after 5 PM
    (df['WEEKDAY NUM'].isin([5, 6]))                 # Saturday or Sunday
).map({True: 'Yes', False: 'No'})

# Drop intermediate columns if desired
df.drop(['hour'], axis=1, inplace=True)

df.head(2)

,CASE#,DATE OF OCCURRENCE,BLOCK,IUCR,PRIMARY DESCRIPTION,SECONDARY DESCRIPTION,LOCATION DESCRIPTION,ARREST,DOMESTIC,BEAT,WARD,FBI CD,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION,WEEKDAY,WEEKDAY NUM,WEEKEND
0,JH117298,2024-01-16 01:00:00,038XX W DIVERSEY AVE,0810,THEFT,OVER $500,STREET,N,N,2524,35,06,1150337.0,1918345.0,41.931844,-87.722951,"(41.931843966, -87.722950868)",Tuesday,1,No
1,JG561057,2023-12-31 16:30:00,004XX N WABASH AVE,0460,BATTERY,SIMPLE,STREET,N,N,1834,42,08B,1176592.0,1902931.0,41.888994,-87.626935,"(41.888993854, -87.626934833)",Sunday,6,Yes